#include "Enclave_t.h" /* Generated by edger8r */
#include "sgx_trts.h"  /* From SGX SDK */

int ecall_generate_random_number()
{
    sgx_status_t ecall_status;
    ocall_print("[Enclave.cpp][Enclave_t.h] <ocall_print>");
    ocall_print("Processing random number generation...");
    uint32_t number;
    // 4 bytes for a 32-bit integer
    sgx_read_rand((unsigned char *)&number, 4);
    return number;
}
